services:
  # Main Frappe Web App Service
  - type: web
    name: rhema-daycare-web
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter # Free tier might lack RAM requirements for building assets
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: frappe-db
          property: host
      - key: REDIS_CACHE_URL
        fromService:
          type: pvt
          name: redis-cache
          property: host

  # Private Redis Cache Service
  - type: pvt
    name: redis-cache
    env: redis
    plan: free

# Database Instance Required by Frappe
databases:
  - name: frappe-db
    plan: free
